FROM debian:9
WORKDIR /nativebinaries
COPY . /nativebinaries/

RUN dpkg --add-architecture armhf

RUN apt update \
&& apt -y install cmake pkg-config \
   crossbuild-essential-armhf

CMD ["/bin/bash", "-c", "./build.libgit2.sh"]
