FROM --platform=$BUILDPLATFORM tonistiigi/xx AS xx

FROM --platform=$BUILDPLATFORM alpine

COPY --from=xx / /

RUN apk add cmake clang lld

WORKDIR /nativebinaries
COPY . /nativebinaries/

ARG TARGETPLATFORM
RUN xx-apk add musl-dev gcc bash

RUN cmake $(xx-clang --print-cmake-defines) ..

CMD ["/bin/bash", "-c", "./build.libgit2.sh"]