FROM --platform=$BUILDPLATFORM tonistiigi/xx AS xx

FROM --platform=$BUILDPLATFORM alpine

RUN apk add cmake clang lld

WORKDIR /nativebinaries
COPY . /nativebinaries/

ARG TARGETPLATFORM
RUN xx-apk musl-dev gcc

CMD ["/bin/bash", "-c", "./build.libgit2.sh"]