FROM --platform=$BUILDPLATFORM tonistiigi/xx AS xx

FROM --platform=$BUILDPLATFORM alpine

COPY --from=xx / /

RUN apk add cmake clang lld bash build-base pkgconf

WORKDIR /nativebinaries
COPY . /nativebinaries/

ARG TARGETPLATFORM
RUN xx-apk add musl-dev gcc 

RUN xx-info env

CMD ["/bin/bash", "-c", "./build.libgit2.sh"]